---
# tasks file for unattended-upgrades

- name: Assertions
  assert:
    that: ansible_pkg_mgr == 'apt'

- name: apt install unattended-upgrades
  with_items:
      - apt-listchanges
      - unattended-upgrades
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Configure
  with_fileglob:
      - '{{ role_path }}/templates/apt.conf.d/*'
  template:
      src: '{{ item }}'
      dest: /etc/apt/apt.conf.d/
      owner: root
      group: root
      mode: 0o0644
